#!/bin/bash
set -e

DEST=$1

go build \
	-o "$DEST/docker-$VERSION" \
	"${BUILDFLAGS[@]}" \
	-compiler gccgo \
	-gccgoflags "$LDFLAGS $LDFLAGS_STATIC_DOCKER" \
	./docker
echo "Created binary: $DEST/docker-$VERSION"
ln -sf "docker-$VERSION" "$DEST/docker"

hash_files "$DEST/docker-$VERSION"
